#Procedural Dungeon Generator demo

##Cellular Automata

####Work in progress still.

I've made a cave map generator using cellular automata heuristics. You've seen conway's game of life, right? Basically like that.

Here's basically how it works:

* Fill the map randomly with walls, based on a given percentage
* For N generations of the map: (helps to do multiple passes)
  * for each location on the map
    * if it's on the border of the map, it's a wall
    * if it's already a wall and has enough walls neighboring it... it's a wall
    * if it's not already a wall and has enough walls neihboring it is also a wall.



Here's a random generation of a 100x100 map:
```
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX  XXX  X     XX X X XX XX  X  XXXXXXX     X  XX  XXXX
XX XX X   XX  XX XXX  XX  XX  X X  XX X     X    X X X X   X
X  XX XXX X XXX   XX   X X XXX  XXX    XXXXX   XXXXXXX    XX
X  X X XX XX XX X XXXXXXX  X XXXX X XXX XX  XX   XXX  XX  XX
XXXXX   X    XX X XXX  XXXX XXXX X  X XXX  X   XX X    X XXX
X XXX XXXX X X X  X XXXXX X XX XXX XXX   XX   XX   X  XX XXX
XX X XX X X  XX XX  X X XXXXXX   XX XX  XX XXX     XXX  XXXX
X X XXX XX X  XX X XX    XX X X X  XXXXX    X XX    XXX X  X
XX        X XX   X X XX X X X X  X X  X  XX  XX XX  X   XX X
XXXX  XX XXX XX   XXXX X   X    XXXX   XX XX X XXXX  XXXXX X
X X  XXXXXX        XXX XXX  XX  X X XX  X   XX  X   XX  XX X
X X X   X  XX  XXXXX XX X   XX X   X XX  XX  X XX  XX XXX XX
X  X  X X XX   X X X XXXX  X  X   XXXX  X X  X XXX   XXX XXX
X   XXX    XXXXX  X XX X XXX     X   X X  X X XX X  XX XXXXX
X   XXX    XXXX X X XX  XXXX XX    XX XXXXXX X X XXXXXX X  X
X XX   X X XXXX  X X   X   XXXXXX   X  X X XX    X XX X X XX
XXXXX XX        X XX  XX  XXXXXX   X XXXX      X      X XXXX
XX X  X X  X X   XXXX     XX  X X XX X XXXXXX X   XXXXX    X
XX  X X  XX XXX      XX XXX X XXX    XXXXXX XX X XX X XXXXXX
X    X     X X XX  XXXX   X XX    XX  X  X    X         XX X
XX X  X  X  XX   X  XXXXX X X X X XXX  XXXX  XXX   XX  X X X
X X     XX    XXX X X   XXXX X  XX X    X X X XX X X   XXX X
XXX XXXX XXX X X X  X    XXX  XXX X   X  X  X   X  XXXXXXXXX
XX XXXX X XXXX X X  XXXXX  X    XX X X  XX   XX        X XXX
X X     X XX  XXX  X   X X  X X XXX XXXXX  XX X     XXX    X
XX  XX  XX XXXXXX X XXXXX X   XXX   XX X XX  XX XX XX      X
X    X   X XXX  X  X X XX XX X    X      XX  X XXX   X  X XX
X    X X XXX X XXX   X XX   XXX XXXX XX    X XXXXX  XX X   X
X X X      XX  X  X   XXXX XX  XXXXX  XX XX  X  XX  X    X X
X                                                          X
X X XX XXXXX  X   XX  X  X  X   XX X X    XXXXX  XX X X    X
X XX   X XX XX   XX  X XX      XXX  X  X  XXX XXX XXX  XX  X
XXXXX X  X X X XXXX  XX XX  X XXXXXXXX  XX  XX  X X   X  XXX
XX  X  XXXX  XXXXXXXXXX   X   X X X X XX  XXX X   X  X     X
X   X    XX  X XXX   XXX X XX XXX  XXX  XXX XX    X XXXX XXX
XX      X    X XX X X    XX  XXX  XX   XX X X XXXX  X   X XX
XX XX X X  XXX      X    XX     XXXXX X X   XX  X  X  XXX XX
X  X      X   X X X XX  X XX X   X X XX   X X     X  XX  XXX
X    XX  X  XXX X  XXX XX  XX  X    X X   XXXX   X     XXXXX
X  X    XX  XXXXXXXX X   XXXX X XXXX XX XX X XX   X X X X XX
XXX X  XXX      XX X XX X  XX  XXX X  X XXX        XXX    XX
X XXX X  X   XXX        XXX X XX    X   XXXXXXX X XXXXX    X
XXX XX     XXXXX  XXX  XX XXX     XXXXXX X   XX X XX X XXXXX
XX XX  X    X  XXXX  X X XX XXX X X  XX XX  XX X      X  XXX
XXX XX    X   X  XX     X  X X X     X XXXX XXX XXX XXXX X X
X X  X  X X    X   XX X     XXX XX  XX  XX X  XXX   XX  X XX
XX XX X  XXX  XXX   XX  X  X     X   XXX XXXXXX  X XXX X   X
X X   XX    X  XX XX     XXX X X X  XX   X X  X XXX   XXX XX
X X     XX    X X   X X X   X   XXXX  X  XX  X    X   X X  X
XXXX X       XX X  X X XXXXXX XXXXX  X X XXX X XX   XXXX  XX
X  XX  XX X XX X XX XX XXXXX  X   XXXXX  XXXX X X   XX     X
XX  XX XX X XX  XXXX  XX  X XX X  XXXXXX  X   XXXX    X  XXX
XX XX XXXX X  X  X X XX  XXXX X  X   XX X     X  XX X  XX XX
X  XXX XXX XXX X XX  XXXXX X XX X  XXX   XXX   X XXX X X XXX
XX  X      XX XX X X  XX XXXXX     X XX XXXXXXX X X X XX   X
XX XX   XXXXXX     X X  X X X X  X X    X X X  X XX  XXX XXX
XX X  XXXXXXXX    X  XXXX      XX X XX      XX    X   X X XX
X XX X   X XX   X XX   X X X X X   XXXX XX XX  X    XXX X  X
```


And after the map generation it turns more like this:
```
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       XXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX      XXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     XXXXXXX
XXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXX
XXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXX
XXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXX
XXXXXXXXXXXXXXX    XXXXXXXXXXXXX  XXXXXXXXXXXXXXX    XXXXXXX
XXXXXXXXXXXXXXXX   XXXXXXXXXXXX    XXXXXXXXXXXXXXX  XXXXXXXX
XXXXXXXXXXXXXXXX    XXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX  XXXX       XXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX    XX          XXXXXXXX    XXXXXXXXXXX  XXXXXXXXXXX
XXXXXXXX    XX           XXXXXXX     XXXXXXXXX    XXXXXXXXXX
XXXXXXX     XXX          XXXXXXX     XXXXXXXXX        XXXXXX
XXXXXX      XXX         XXXXXXXX      XXXXXXXXX        XXXXX
XXXXX        XXX        XXXXXXXXX      XXXXXXXXX       XXXXX
XXXXX         XXX       XXXXXXXXXX      XXXXXXXX      XXXXXX
XXXXXX        XXX       XXXXXXXXXXX     XXXXXXXX      XXXXXX
XXXXXX        XXX       XXXXXXXXXXXX   XXXXXXXXX       XXXXX
XXXXX        XXXX      XXXXXXXXXXXXXXXXXXXXXXXXX         XXX
XX          XXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXX         XX
X           XXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXX         XX
X            XXX      XXXXXXXXXXXXXXXXXXXXXXXXXX          XX
X                      XXXXXX  XXXXXXXXXXXX                X
X                               XXXXXX                     X
XX                              XXXXX                      X
XXX                            XXXXXX                     XX
XXX            XX              XXXXXXX     XX             XX
XX            XXXX             XXXXXXX    XXXX            XX
XX            XXXX             XXXXXXX    XXXX           XXX
XX             XX              XXXXXXX     XXX           XXX
XX                              XXXXXXX    XXX           XXX
X                                XXXXXX    XXX          XXXX
X              XX  XX            XXXXXXX  XXXX          XXXX
XX            XXXXXXXX           XXXXXXXXXXXXX           XXX
XXXX          XXXXXXXX           XXXXXXXXXXXXX           XXX
XXXXX        XXXXXXXX             XXXXXXXXXXXXX         XXXX
XXXXX        XXXXXXXX              XXXXXXXXXXXX       XXXXXX
XXXXX         XXXXXX                XXXXXXXXXXXX     XXXXXXX
XXXXX          XXXXX                XXXXXXXXXXXXX   XXXXXXXX
XXXXXX         XXXXXX               XXXXXXXXXXXXX   XXXXXXXX
XXXXXX         XXXXXX               XXXXXXXXXXXXXX   XXXXXXX
XXXXX          XXXXXX               XXXXXXXXXXXXXX   XXXXXXX
XXXXX          XXXXXX               XXXXXXXXXXXXXX   XXXXXXX
XXXXX           XXXXXX  XXX        XXXXXXXXXXXXXX     XXXXXX
XXXXXX          XXXXXXXXXXXX      XXXXXXXXXXXXXXX       XXXX
XXXXXXX         XXXXXXXXXXXXX     XXXXXXXXXXXXXXXX       XXX
XXXXXXX         XXXXXXXXXXXXXX     XXXXXXXXXXXXXXXX      XXX
XXXXXXX          XXXXXXXXXXXXX     XXXXXXXXXXXXXXXXX      XX
XXXXXXXX   XX     XXXXXXXXXXXX      XXXXXXXXXXXXXXXX      XX
XXXXXXXXXXXXXX    XXXXXXXXXXXX      XXXXXXXXXXXXXXXX      XX
XXXXXXXXXXXXXXX  XXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXX    XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

```